# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: ubuntu:latest

before_script:
  - echo "Before script section"
  - echo "For example you might run an update here or install a build dependency"
  - apt-get update && apt-get -y upgrade git
  - git config --global user.email "300098957@collegeboreal.ca"
  - git config --global user.name "b300098957"
  - echo $CI_JOB_TOKEN
  - git remote --verbose
  - url_host=`git remote get-url origin | sed -e "s/https:\/\/gitlab-ci-token:.*@//g"`
  - git remote set-url origin "https://gitlab-ci-token:${CI_TAG_UPLOAD_TOKEN}@${url_host}"
  - git remote --verbose
  
after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

build1:
  stage: build
  script:
    - echo "Do your build here"

test1:
  stage: test
  script:
    - echo "Do a test here"
    - echo "For example run a test suite"

test2:
  stage: test
  script:
    - echo "Do another parallel test here"
    - cd 4.Strings
    - echo `pwd`
    - bash .scripts/participation.sh > .scripts/Participation.md 2>&1
    - git status
    - git add .scripts/Participation.md
    - git commit --message "adding participation"
    - git status
    - git push origin master

deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
    - git status
